more testing

diff --git a/.github/workflows/package.yml b/.github/workflows/package.yml
--- a/.github/workflows/package.yml
+++ b/.github/workflows/package.yml
@@ -72,34 +72,58 @@ jobs:
       version: ${{ steps.distribution.outputs.version }}
 
   image:
-    name: Build and publish docker images
+    name: Docker images
     runs-on: ubuntu-latest
     needs: pypi_upload
     strategy:
       matrix:
         slim: ['false', 'true']
+        python: ['3.11', '3.12']
 
     steps:
     - uses: actions/checkout@v3
 
     - name: Prepare build config
+      uses: actions/github-script@v7
       id: config
-      run: |
-        if [ -z "${{ needs.pypi_upload.outputs.version }}" ]; then
-          exit 1
-        fi
-        if [ "${{ matrix.slim }}" = "true" ]; then 
-          echo "base_image_tag=3.11-slim-bookworm" >> "$GITHUB_OUTPUT"
-          echo "tag_suffix=-slim" >> "$GITHUB_OUTPUT"
-        else
-          echo "base_image_tag=3.11-bookworm" >> "$GITHUB_OUTPUT"
-          echo "tag_suffix=" >> "$GITHUB_OUTPUT"
-        fi
-        if [ "${{ env.IS_RELEASE }}" = "true" ]; then
-          echo "pypi_index=https://pypi.org/simple" >> "$GITHUB_OUTPUT"
-        else
-          echo "pypi_index=https://test.pypi.org/simple" >> "$GITHUB_OUTPUT"
-        fi
+      with:
+        script: |
+          const slim = process.env.SLIM
+          const python = process.env.PYTHON
+          
+          let suffixes = [`-py${python}`]
+          if (python === '3.11') {  // 3.11 is the default python
+            suffixes.push('')
+          }
+          
+          if (slim === 'true') {
+            core.setOutput('platforms', 'linux/amd64')
+            core.setOutput('base_image_tag', `${python}-slim`)
+            suffixes = suffixes.map(item => item + '-slim');
+          } else {
+            core.setOutput('platforms', 'linux/amd64,linux/arm64')
+            core.setOutput('base_image_tag', python)
+          }
+          
+          console.log(`suffixes: ${JSON.stringify(suffixes)}`)
+          
+          let meta_tags_base = [
+            'type=ref,event=branch,suffix=',
+            'type=semver,pattern={{version}}',
+            'type=semver,pattern={{major}}.{{minor}}',
+          ]
+          let meta_tags = suffixes.flatMap(suffix => meta_tags_base.map(t => t + suffix))
+          core.setOutput('tags', meta_tags.join('\n'))
+          console.log(`meta_tags: ${JSON.stringify(meta_tags)}`)
+    
+          if (process.env.IS_RELEASE === 'true') {
+            core.setOutput('pypi_host', 'https://pypi.org')
+          } else {
+            core.setOutput('pypi_host', 'https://test.pypi.org')
+          }
+      env:
+        SLIM: ${{ matrix.slim }}
+        PYTHON: ${{ matrix.python }}
 
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v2
@@ -117,22 +141,41 @@ jobs:
       uses: docker/metadata-action@v4
       with:
         images: mcdreforged/mcdreforged
-        tags: |
-          type=ref,event=branch
-          type=semver,pattern={{version}}
-          type=semver,pattern={{major}}.{{minor}}
-        flavor:
-          suffix=${{ steps.config.outputs.tag_suffix }},onlatest=true
+        tags: ${{ steps.config.outputs.tags }}
+
+    - name: Wait for PyPI index update
+      run: |
+        start_time=$(date +%s)
+        while true; do
+          if curl -s "${PYPI_HOST}/simple/mcdreforged/" | grep "mcdreforged-${VERSION}.tar.gz" > /dev/null; then
+            echo "Version ${VERSION} exists on ${PYPI_HOST}"
+            break
+          else
+            current_time=$(date +%s)
+            elapsed_time=$((current_time - start_time))
+            if [ "$elapsed_time" -ge 600 ]; then
+              echo "Failed to find package version ${VERSION} on ${PYPI_HOST} after 10 minutes"
+              exit 1
+            fi
+            echo "Version ${VERSION} not exist on ${PYPI_HOST}. Checking again in 5 seconds"
+            sleep 5
+          fi
+        done
+      env:
+        VERSION: ${{ needs.pypi_upload.outputs.version }}
+        PYPI_HOST: ${{ steps.config.outputs.pypi_host }}
 
     - name: Build and push
       id: build
       uses: docker/build-push-action@v5
       with:
-        platforms: linux/amd64,linux/arm64
+        platforms: ${{ steps.config.outputs.platforms }}
+        push: false
         file: docker/Dockerfile
         context: docker
         tags: ${{ steps.meta.outputs.tags }}
         labels: ${{ steps.meta.outputs.labels }}
         build-args: |
+          BASE_IMAGE_TAG=${{ steps.config.outputs.base_image_tag }}
           MCDR_REQUIREMENT=${{ needs.pypi_upload.outputs.version }}
-          PYPI_INDEX=${{ steps.config.outputs.pypi_index }}
+          PYPI_INDEX=${{ steps.config.outputs.pypi_host }}/simple
